### PR TITLE
1.x backport: Allows patch-level to be specified per-project.

### LINKED ISSUE #43: Patch  for new file  applied to incorrect location
https://www.drupal.org/files/issues/drupal-migrate_skip_on_value-2711949-2.patch

I'm using drupal-composer/drupal-project and when I try to apply the patch listed above, it creates it as web/core/core/core/modules/migrate/src/Plugin/migrate/process/SkipOnValue.php, etc.

### PR DESCRIPTION
**Pull request by jhedstrom**
- Backport to `1.x`
- Reroll of #101
- Fixes #43

### CODE REVIEW

**Comment by bkosborne** [comment]
Would love to see this in! We're also having issues with applying Drupal core patches that introduce new files. They go to the wrong place.

**Comment by MPParsley** [comment]
Indeed, this should go in 1.x

**Comment by fenstrat** [comment]
This works a treat for core patches. Would also love to see this in 1.x.

**Comment by cweagans** [comment]
Despite what I said before, I'm okay with this. It's pretty low risk and solves some immediate problems for people using composer-patches. While I would really like to say that this is a 2.x feature, the reality is that 2.x isn't moving along as quickly as I'd like, and it's not fair to make people wait for something that doesn't have a realistic release date set.

Thanks for bringing this back up, and sorry I didn't give it more consideration before.

**Pull request merged**
