### PR TITLE
Handle patches-ignore when re-patching

### LINKED ISSUE #112: Ignoring patches from dependencies doesn't work
I'm trying to ignore a patch defined in the composer.json of the Drupal distribution 'Open Social'. 

The setup mentioned in the readme, doesn't seem to work.

This part of the code seems never to be used:
```
 if (isset($extra['patches'])) {
          if (isset($patches_ignore[$package->getName()])) {
            foreach ($patches_ignore[$package->getName()] as $package => $patches) {
              if (isset($extra['patches'][$package])) {
                $this->io->write('<info>ignore patches each:' . implode(',', $patches) . '</info>');
                $extra['patches'][$package] = array_diff($extra['patches'][$package], $patches);
              }
            }
          }
          $this->patches = array_merge_recursive($this->patches, $extra['patches']);
        }
```

And in the following part regardless of ignore definitions dependency patches are added.

```
    foreach ($this->installedPatches as $patches) {
```

### PR DESCRIPTION
**Pull request by christopher-hopper**
## Proposed Changes

Prevent removing a package so it can be re-installed and re-patched just
because patches-ignore is being used. Ensure the patches-ignore are
accounted for when comparing patches with applied patches.

## Related Issues

Fixes #112 

## Notify

- @alexdesignworks 
- @brantwynn

### CODE REVIEW

**Comment by danepowell** [comment]
I haven't had time to test this, but the approach makes sense to me, seems like it would help with #112.

**Comment by christopher-hopper** [comment]
If you're looking to test, these commands may help:

*Use modified package repo*
```sh
composer config repositories.composer-patches \
  git https://github.com/christopher-hopper/composer-patches.git
```

*Require patch-1 branch aliased as v1.6.5*
```sh
composer require "cweagans/composer-patches:dev-patch-1 as 1.6.5"
```

I'm using it now wherever we needed `'patches-ignore'` to remove a Drupal Lightning patch. It's now working as expected.

**Comment by cweagans** [comment]
Thanks for this!

**Comment by brantwynn** [comment]
Thank you so much for this, @christopher-hopper - it's been a pain in our sides for a long time.

**Comment by brantwynn** [comment]
I am trying to use this via the latest dev (HEAD) of this project and I see this error once it gets to patching. 

```  - Applying patches for drupal/core
    https://www.drupal.org/files/issues/2752961-130.patch (Clear Twig caches on deploys)


  [ErrorException]
  Trying to get property 'url' of non-object
```
Has anyone else seen this? Happy to file another issue, but wanted to note that it came up when switching over to the new version.

**Comment by cweagans** [comment]
You're probably using the HEAD of `master`, which you definitely don't want to be doing right now. Use 1.x instead.

**Comment by brantwynn** [comment]
Ahh. Got it. 

Can confirm this is working for us to ignore some of the `acquia/lightning` patches during both `composer install` and `composer update` Ref: https://github.com/acquia/df/commit/a8fddc5684e921b43960fce82ce79d907de7d861

Thanks!

**Pull request merged**
