### PR TITLE
Print error message when patch couldn't be applied

### PR DESCRIPTION
**Pull request by jerbob92**
Yesterday I spent 2 hours looking for the problem.
The only message I got was: ```Could not apply patch! Skipping```
Apparently it was because Composer does not want to download patches over http (since 1.0.0).

This PR makes the error also print the the Exception message..
Old:
image

New:
image

### CODE REVIEW

**Comment by jerbob92** [comment]
@cweagans Could you please review this?

**Comment by jerbob92** [comment]
@cweagans hello?

**Comment by jkenn99** [comment]
@cweagans is there anything blocking this?

**Comment by cweagans** [comment]
Hey folks, sorry for the long delay here. Life and such got in the way. In any case, this looks good, but it might be worthwhile to document this in README.md as well. Thoughts?

**Comment by jerbob92** [comment]
No problem, I can relate to that.
What do you think should be in the README.md? The error display behavior or the secure-http option in Composer?

**Comment by cweagans** [comment]
Oh, specifically the secure-http option.

**Comment by jerbob92** [comment]
Sure, I'll write something up tomorrow.

**Comment by cweagans** [comment]
Cool, I'll take a look when I can. Thanks!

**Comment by jerbob92** [comment]
@cweagans I added the text!

**Comment by cweagans** [comment]
Thanks!

**Pull request merged**
