### PR TITLE
allow binary option and implementation

### PR DESCRIPTION
**Pull request by mamsincl**
fixing issue https://github.com/cweagans/composer-patches/issues/299

`composer.lock` changes as per contributing workflow

### CODE REVIEW

**Comment by mamsincl** [comment]
I try my best to port the solution back to [`1.x`](https://github.com/cweagans/composer-patches/tree/1.x)

**Comment by brucemead** [comment]
+1 this feature is required

**Comment by brucemead** [comment]
@cweagans would you be able to review this please?

**Comment by cweagans** [comment]
See #447 for current 2.x status. I've made a note to ensure that binary patches are supported.

**Pull request closed without merging**
