### PR TITLE
add Travis

### PR DESCRIPTION
**Pull request by TomasVotruba**
If there are tests, why not run them in a CI? :)

Ad it manually here: https://travis-ci.org

Also, I can add a badge for test status

### CODE REVIEW

**Comment by cweagans** [comment]
I have Travis set up in the 2.x branch. Not too interested in doing this for 1.x. There are tests, but it's not comprehensive enough to bother with in this branch.

**Comment by TomasVotruba** [comment]
I see. Why not set 2.x as default then? I didn't see it.

Btw, why master = 1.x, 2.x is dev?
Usually tag-name branch is used for older version to keep bugfixes.

**Comment by cweagans** [comment]
2.x is not 100% functional right now - there's still some work to be done. Eventually, 2.x will be merged into master and 1.x will be no more.

**Comment by TomasVotruba** [comment]
Oh, I see. So it's PR, not a dev branch. That's more clear to me, thank you

**Comment by TomasVotruba** [comment]
Still, when it's opened for such a long time, it should be set as default, so it's clear where to commit: https://github.com/cweagans/composer-patches/branches

You see all people comiting to master: https://github.com/cweagans/composer-patches/pulls

**Comment by cweagans** [comment]
master is the default because that's what people are using right now. 2.x is not usable for actually patching things at this point, so I don't want to add confusion.

**Comment by TomasVotruba** [comment]
I see.

When do you plan to merge this?

**Comment by cweagans** [comment]
When it's ready ;) Honestly, I don't know. I've been working on 2.x for quite a while now, but it's pretty bottlenecked on my free time right now. The remaining stuff is pretty straightforward, but it's time consuming to test everything as I write it.

**Comment by TomasVotruba** [comment]
I see. Anything I can help with? :)

**Pull request closed without merging**
