### PR TITLE
Don't return early on install unless dependencies don't supply patches either

### LINKED ISSUE #71: Patches added to dependency after initial install not applied to root package on update
Steps to reproduce:
- Add a dependency to your root package which contains patches
- Add a new patch to that dependency
- Run composer update my/dependency in your root package

Expected:
New patch is applied

Actual:
New patch is not applied

### PR DESCRIPTION
**Pull request by acbramley**
Fixes #71 

However this may be inefficient, keen to get feedback on this.

### CODE REVIEW

**Comment by Berdir** [comment]
Just noticed this too, the documentation currently claims this is possible but it is actually not. 

Works. I don't see a performance problem, if you get to that point, you already explicitly opted in to patching some way or another.

**Comment by codebymikey** [comment]
This change has been applied on the https://github.com/cweagans/composer-patches/commit/d9d31d812d483cefbae89238e52ba2a25d8a1cbb commit and the PR can be safely closed.

**Comment by acbramley** [comment]
@codebymikey curious why this PR wasn't just merged?

**Comment by codebymikey** [comment]
No idea, I'm not a maintainer of the project.

I just found this PR thinking it would address an issue I was having with patches not applying on initial install.
Then upon attempting to apply the patch, noticed it was already applied a few years back in a different commit, so thought I'd document it here and clean up the list of open PRs.

**Comment by acbramley** [comment]
Haha cheers, didn't realise you weren't a maintainer :)

**Pull request closed without merging**
