### PR TITLE
Adds patch options support, with binary option already implemented

### PR DESCRIPTION
**Pull request by alepane21**
Hi, I need the ability to patch some module made in code with \r\l line endings. The only clean way to do it, without using git apply, is to use the binary option on patch. With git apply you can prepare a binary patch with git format-patch, but I cannot do it because our module is not versioned with git. What a wild world we live in!
So my only option was to fork your nice code and try to add the ability to specify some patches as binary.
Let me know if there are things that you don't like and should be fixed, thanks!

### CODE REVIEW

**Comment by andypost** [comment]
+1 to add support for binary patches

**Comment by yaroslav-qlicks** [comment]
it is cool feature, why it is still not merged?

**Comment by brucemead** [comment]
+1

**Comment by awm086** [comment]
+1

**Comment by cweagans** [comment]
I've made a note to include this in #447.

**Pull request closed without merging**
