### PR TITLE
Added circle CI support.

### PR DESCRIPTION
**Pull request by thom8**
Adding additional tests and support for Circle CI.

Example build -- https://circleci.com/gh/thom8/composer-patches/14

### CODE REVIEW

**Comment by thom8** [comment]
Also allows running tests locally with `composer test`

**Comment by cweagans** [comment]
We already have Travis CI. What does Circle CI get us?

**Comment by thom8** [comment]
Ah, sorry my bad didn't notice the `2.x` branch.. 

Will check out the test suite on `2.x` and see if there's any benefits to Circle over Travis for this project. I've found builds times to be ridiculously fast with circle v2, faster to push than running locally, then end up doing debugging via SSH on their env.

**Comment by thom8** [comment]
BTW here's a build with git `2.14.2` -- https://circleci.com/gh/thom8/composer-patches/22

image

but my test coverage is probably not good enough to pick up the issue..

**Comment by thom8** [comment]
Closing as this will need rebasing with HEAD.

**Pull request closed without merging**
