### PR TITLE
Re-install a package that got removed due to patch changes

### LINKED ISSUE #26: Package deleted but not reinstalled and patched
This is happening on both Composer install\update after I've initially updated the patches file. The next time I run an install or update however the package is reinstalled and patched as expected. 

This is the terminal output when the package is not reinstalled:

Image of terminal output

The extra section of my composer.json

``` json
"extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        },
        "merge-plugin": {
            "include": [
                "web/modules/custom/*/composer.json"
            ],
            "recurse": true,
            "replace": false,
            "merge-extra": false
        },
        "patches-file": "composer.patches.json"
    }
```

and my composer.patches.json

``` json
{
  "patches": {
    "drupal/devel": {
      "Patch title": "https://www.drupal.org/files/issues/wrong_dependencies_are-2629828-6.patch"
    }
  }
}
```

### PR DESCRIPTION
**Pull request by jurgenhaas**
This should fix #26

### CODE REVIEW

**Comment by mglaman** [comment]
I'm noticing this often, which is leaving me with impartial builds; causing us to run `composer update` or `composer install` twice when moving around patches.

**Comment by grasmash** [comment]
This appears to re-install but not re-patch.

**Comment by grasmash** [comment]
#26 is better resolved by #30.

**Comment by waleedq** [comment]
I know that you've dropped support for 1.x, but this issue is still not solved by #30, #30 would solve the re-patch issue for the removed packages, but sometimes the composer is not re-installing the deleted packages for some reason! so i guess this is needed to make sure the package is installed after getting removed.

**Pull request closed without merging**
