### PR TITLE
Better deal with core patches if core is installed in a sub directory

### PR DESCRIPTION
**Pull request by mkalkbrenner**
should fix https://github.com/cweagans/composer-patches/issues/60

### CODE REVIEW

**Comment by hostep** [comment]
@mkalkbrenner: please be aware that this module isn't only for patching Drupal projects, it is supposed to be a generic composer plugin for patching all kinds of projects. We are using it for Magento2 projects for example.

Please correct me if I'm wrong, but this PR seems to be targeting Drupal projects, so this change feels very wrong to me...

**Comment by cweagans** [comment]
Yep, what @hostep said. I don't want to add things like this for specific projects.

**Comment by mkalkbrenner** [comment]
I understand that you don't want to have drupal specific stuff.
But the hard-coded order of p1, p0, p2 is really bad if you use https://github.com/drupal-composer/drupal-project for your drupal project.
So what should we do? Maintain a fork of composer-patches?
A different approach would be to have a setting, which options should be tried in which order.
That would also solve https://github.com/cweagans/composer-patches/pull/136

**Comment by cweagans** [comment]
2.x will let you set the p value on a per-patch basis.

**Pull request closed without merging**
