### PR TITLE
Use --git-dir instead of GIT_DIR env variable

### LINKED ISSUE #106: Removing GIT_DIR=. from patch apply broke functionality on unix when installing dist packages
Before I could install packages from dist and the patches would apply, since PR #104 was merged, this doesn't work. This is clearly described in the documentation:
```
GIT_DIR is the location of the .git folder. If this isn’t specified, Git walks up the directory tree until it gets to ~ or /, looking for a .git directory at every step.
```

### PR DESCRIPTION
**Pull request by daften**
Fixes #106 with another method than #107 
This works on unix, but would need to be tested on windows, I'm hoping @david-garcia-garcia and @celston can help with that? :)

### CODE REVIEW

**Comment by david-garcia-garcia** [comment]
I tried the command syntax directly on the console, and it - at least- does not break on windows. Still not sure why we need to use --git-dir at all. We are cd'ing in order to place ourselves in the directory where the git root is supposed to be.

**Comment by cweagans** [comment]
Sometimes there is no git root (i.e. if installing from dist). I prefer this pr over #107, fwiw.

**Comment by daften** [comment]
Yes, if there's no git root inside the package to be patched, this makes sure that's possible.
This is my preferred option too, since it should work cross platform, but it only came to me after I made the other PR :)

**Comment by dmsmidt** [comment]
This should get top priority, without it patching on Linux is broken. 
I tested manually on Linux and it works.

**Comment by REBELinBLUE** [comment]
Any update on this? Patching is completely broken when trying to patch dist packages

**Comment by REBELinBLUE** [comment]
:D Thanks @cweagans

**Pull request merged**
