### PR TITLE
Add support for local patches.

### PR DESCRIPTION
**Pull request by tobiasbaehr**
I tried it with file:///patches/mypatch.patch but this do not work with parse_url.

### CODE REVIEW

**Comment by cweagans** [comment]
:+1:

**Comment by yched** [comment]
Awesome, support for local patches would be definitely precious.

However, we'd need a way to trigger a module repatch if the content of the local patch file changes (which is not really an issue with remote patches, since we can assume "same url = same content")

That probably means storing a hash of the file content in installed.json when applying the patch,, so that we can compare the next time around.

**Comment by yched** [comment]
Oops, crosspost :-)

**Comment by cweagans** [comment]
@yched You're right. This is a good first pass, though. We can implement the re-patch functionality in another PR. I think it's reasonable to get a hash of every patch (local or remote) and store it. That way, we know if a remote hash has changed too. Getting that into place simplifies https://github.com/cweagans/composer-patches/issues/19 as well.

That said, I want to refactor the plugin quite a bit. `Patches.php` has like 10 separate jobs that it's doing, and if it were broken out into smaller pieces, it'd be a lot more testable, IMO. The bigger this plugin gets, the more scared I am to just merge a PR. I don't want to go too much further down this path without having a pretty solid test suite in place.

**Comment by yched** [comment]
Also, I cant test right now, but according to http://php.net/manual/en/function.file-exists.php,  file_exists() also works with 'http://...' urls ? So the code here doesnt actually differentiate between local and remote patches ?

**Comment by cweagans** [comment]
Ugh. wtf php.

How about `is_file() && is_readable()` ?

**Comment by yched** [comment]
Sorty, my bad.
http://php.net/manual/en/wrappers.http.php says "Supports stat() : No". 

So file_exists() should be ok :-)

**Pull request merged**
