### PR TITLE
optionally prefer patch util over git apply

### PR DESCRIPTION
**Pull request by mkalkbrenner**
In our projects in happens very often that git apply doesn't succeed but the patch utility fallback does.
This PR introduces an prefer-patch-util option for the extras section. If set to true, the patch util is tried before git apply.

### CODE REVIEW

**Comment by LionsAd** [comment]
+1 looks great to me!

**Comment by cweagans** [comment]
I would prefer to not add a configuration option for this. `git apply` fails, but then `patch` succeeds. Why not just let `git apply` fail in this case? The patch gets applied properly eventually.

**Comment by mkalkbrenner** [comment]
> Why not just let git apply fail in this case?

In our case we handle a lot of patches in our projects. In case that there's a problem with one patch that forces you to switch to the verbose mode you can't see anything because the log if full of error messages. You simply can't find the important part rapidly.
If you can switch the strategy to the one that better fits your project using this PR, the log turns "green" completely, even in verbose mode.
Now, if something goes wrong and you turn on verbose logging you get exactly one "red" part that directly points you to the cause.
That's the story why I created this PR.

As a side effect you have a slight performance benefit.

**Comment by cweagans** [comment]
In 2.x, you can disable the Git patcher or you can write an event subscriber to reorder them. #447

**Pull request closed without merging**
