### PR TITLE
Issue #258: Remove patch report generation (PATCHES.txt) - backport for 1.x.

### LINKED ISSUE #258: Backport the removal of PATCHES.txt to 1.x branch
In issue #140 / PR #213, the patch report generation (PATCHES.txt) was removed for the 2.x branch.
A release in this new branch has not happened yet.

I am going to provide a PR that backports this change to the 1.x branch.

### PR DESCRIPTION
**Pull request by donquixote**
This is a backport of pull request #213 for issue #140.
The two commits from #213 have been squashed into one.

Fixes #258.

### CODE REVIEW

**Comment by alisonjo315** [comment]
This would be cool!

**Comment by alisonjo315** [comment]
needs a rebase I think, ya?

**Comment by cweagans** [comment]
FYI, you can do this with a config option: https://github.com/cweagans/composer-patches/tree/1.x#patches-reporting

**Comment by cweagans** [comment]
Not going to merge this. You can disable with a config flag + this functionality is removed in #447 anyway

**Pull request closed without merging**
