### PR TITLE
isPatchingEnabled() checks 'patches-file' too

### PR DESCRIPTION
**Pull request by calin-marian**
isPatchingEnabled() will also take into consideration 'patches-file' when determining if root package uses patches.

I use the patches-file setting in the composer.json file, and after upgrading to 1.5.0 my patches were not applying anymore. I followed the code to the isPatchingEnabled(), where if enable-patching is not set, it will default to true if the root package uses patches, and to false otherwise.

However, detecting if the root project uses patches was done only based on the 'patches' key.

This PR checks also if 'patches-file' exists to determine if the root project uses patches.

### CODE REVIEW

**Comment by calin-marian** [comment]
#45 is related.

**Comment by adragus-inviqa** [comment]
Wasted a couple of hours because of this. Please merge already.

@calin-marian - care to fix the conflicts?

**Comment by calin-marian** [comment]
I updated the code, no more conflicts.

**Comment by cweagans** [comment]
Sorry for the super long delay on this. I preferred an isset() here, so I fixed this in https://github.com/cweagans/composer-patches/commit/a7e3ebe4d84891b9865d3d7a7120391d079af5eb. This will be included in the next release, which should be out in the next few minutes.

**Pull request closed without merging**
