### PR TITLE
Add installedPatches property to fix PHP 8.2 deprecation 1.x version

### PR DESCRIPTION
**Pull request by seamuslee001**
This is the 1.x version of #409

### CODE REVIEW

**Comment by nesl247** [comment]
Any chance for this to be merged? Is this project maintained anymore?

**Comment by joelpittet** [comment]
RTBC++ 🚀

**Comment by danepowell** [comment]
@cweagans this is necessary for PHP 8.2 compatibility, would you mind reviewing?

**Comment by vd-lhridley** [comment]
Can we get a new release for the 1.x version with this patch applied?  It seems that patching the package with a diff doesn't work, I'm guessing because this package is responsible for managing the patch process, and it can't patch itself.

**Comment by cweagans** [comment]
https://github.com/cweagans/composer-patches/releases/tag/1.7.3 includes this. Are you seeing something different?

**Pull request merged**
