### PR TITLE
Add support for patch checksums

### PR DESCRIPTION
**Pull request by ceesgeene**
As the status of version 2 is not clear to me, this is a PR against 1.x instead of the master branch. It would be nice if we could have this feature in version 1.

This PR is based upon #163 . That PR no longer matches. Biggest difference is that this PR keeps using the key as description. Also instead of hash, the term checksum is used.

### CODE REVIEW

**Comment by mxr576** [comment]
First of all, I am thrilled that there is some movement on this topic :tada: How Composer Patches could be leveraged in supply chain attacks was one of those problems that concerned me the most in the past year(s), but my focus was always shifted so I could not work on these problems. Also, @cweagans made it quite clear on [Twitter](https://twitter.com/cweagans/status/1430664598319890432) that no matter how much the PHP community (not just Drupal developers) [depends on this package](https://packagist.org/packages/cweagans/composer-patches/stats), it is not minimally maintained, and _there is no problem with that_. Although, that made me realize that a community effort and support are needed to provide at least the minimum necessary care to this valuable library. Something similar that was formulated around https://github.com/php-tuf/php-tuf.

Maybe that will happen now, and I would be glad if I could be part of that effort.

**Comment by mxr576** [comment]
As I said in https://github.com/cweagans/composer-patches/issues/347#issuecomment-1004603765 I am really happy that there is some movement around this topic, so thanks for this PR.

What I like about this approach that it is _simple and straightforward_. What I do not like that it is opt-in feature and security must not be optional. So I started to think about how we can have this security feature enabled by default.

We have two significantly different scenarios, when a patch is installed from a local source or from a remote URL. We only have problems with remote patch sources because in general, we cannot trust that the content of a patch does not change on a remote. If a patch is served from the local filesystem that was potentially downloaded _and verified_ by a human, hopefully also passed on a code review and it is part of a VCS repo. Why do I think it is essential to differentiate these two scenarios? The reason is that if hash based protection is enabled by default and it would also be applied on local patches, then I think it could become a bottleneck because the content of those patch files can rightfully change anytime and no additional steps (like running `composer update-composer-patch-hash ./path-to.patch`)  should be required for updating a local patch file.

So if we would like to auto-generate hashes (with a preferred algorithm) of newly added _remote_ patches, how can we do that?

When I saw these manually generated hashes, it made me remember again that with Composer 1, all applied patches [were listed in composer.lock also](https://github.com/DrupalOpenLearning/drupalopenlearning/blob/7a46c10e36fce58afc2c2320663f523e8457fa54/vendor/composer/installed.json#L1926). I am not sure how and why that changed with Composer 2 but my opinion is that auto-generated hashes should be in composer.lock, just like [hashes of downloaded packages](https://github.com/DrupalOpenLearning/drupalopenlearning/blob/7a46c10e36fce58afc2c2320663f523e8457fa54/vendor/composer/installed.json#L1908).

When a new patch is added and `composer install` or `composer update` is executed, then Composer Patches plugin could generate hashes for remote patches that did have hashes before. This also implies that the URL of a remote patch is considered unique, which was avoided here as a design decision, but is it a good idea? When a diff of a Gitlab MR is referenced and the MR changes what we want is make the build failed because it is a _mutable_ (non-static) reference.

In which circumstances we need hashes in `composer.json`? I can imagine one common scenario when patches are distributed via libraries/modules ([example 1](https://github.com/nwuatmath/drupal/blob/ce1d6481f4f8e075977cc053714a252f36a64c37/lightning-8.x-3.200/modules/contrib/lightning_layout/composer.json#L79-L90)) by leveraging the `enable-patching: true` feature of Composer Patches (which is another [open door for supply chain attackes](https://github.com/cweagans/composer-patches/issues/354#issuecomment-1004759055)). In that scenario, the package provider probably also would like define a hash for every  _remote_ patch "suggested" by the library so whenever patches are installed on a project, Composer Patches could verify that the content of a proposed patch is the same as it was when it had been added.

What are others thinking about these ideas?

(Possibly the easiest and safest option would be only supporting local patches :grin: )

**Comment by cweagans** [comment]
Thank you for opening this -- I'm swamped but will review ASAP. Thank you @gapple for the original PR as well.

One (hopefully) quick thing: let's just pick a hashing algo and only support that one. sha256 seems like a good candidate, but I'm open to other options. I'd prefer to reduce the number of possible configurations + limit the scope of this change as much as possible.

**Comment by ceesgeene** [comment]
I agree on limiting the scope as much as possible; refactored the PR so it only supports sha256 checksums.

**Comment by bbrala** [comment]
This really would be awesome to get moving. This would be an awesome step forward, even though there is probable next steps to make this even more automated.

**Comment by ceesgeene** [comment]
@cweagans, haven't found the time yet, or is something regarding the PR holding you back?

This is an attempt to push this pull request  :)

**Comment by korkhau** [comment]
The time for merge is come.
@cweagans please do :)

**Comment by cweagans** [comment]
#447 has this.

**Pull request closed without merging**
