### PR TITLE
#218 - Correctly resolve relative local paths pointing to patch files from dependencies - Follow up

### PR DESCRIPTION
**Pull request by drupol**
This is an updated version of PR #218.

### CODE REVIEW

**Comment by drupol** [comment]
I don't know why the coveralls is not triggered anymore but the coverage have increased since I added the tests.

**Comment by rlmumford** [comment]
Is this just waiting on the test coverage?

**Comment by yanniboi** [comment]
I would also love to see some progress on this. Anything we can do to push it forward?

**Comment by drupol** [comment]
Yes I think increasing the test coverage would be a nice and the maintainer will be pleased.

**Comment by rlmumford** [comment]
@drupol unfortunately I've never worked with coveralls before and I'm not sure what would be required to increase that coverage stat.

**Comment by drupol** [comment]
You do not need coveralls, you just need to write more tests, coveralls will compute the coverage by itself.

**Comment by iamweird** [comment]
This PR seems to be obsolete due to https://github.com/cweagans/composer-patches/pull/267.

**Comment by louis-cuny** [comment]
I would be happy to see this PR merged, how can I help ?

**Comment by cweagans** [comment]
Resolving patches from dependencies isn't a thing in 2.x, so neither is applying patches stored relative to the root of a dependency.

**Pull request closed without merging**
